title: "Arya Hariharan"
author: "Arya Hariharan"
description: "CS student at R.V. College of Engineering | ML & AI Safety Research"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: false
show_sidebar: false
show_minimal: false

# Menu
navigation:
  - {file: "archive.html", title: "Home",   sidebaricon: home}
  - {file: "about.md",     title: "About",  sidebaricon: address-card}
  - {file: "papers.md",    title: "Papers", sidebaricon: book-open}
  - {file: "resume.md",    title: "Resume", sidebaricon: file-alt}

external:
  - {title: Mail,     icon: envelope, url: "mailto:arya.hariharan2004@gmail.com"}
  - {title: Github,   icon: github,   url: "https://github.com/Arya-Hari"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/arya-hariharan-b0327a205"}

plugins:
  - jekyll-feed
